import type { ToolExamples } from "../mcp/contract.examples.js"

export const downloadExamples: ToolExamples = {
  gangtise_download: [
    { title: "summary", args: { kind: "summary", id: "sum-1", fileType: 2 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/summary/v2/download/file", query: { summaryId: "sum-1", fileType: "2" } }] } },
    { title: "summary：不收 contentType", args: { kind: "summary", id: "sum-1", contentType: "asr" }, expect: { rejects: /不收 contentType/ } },
    { title: "pamirs_summary", args: { kind: "pamirs_summary", id: "pam-1" }, expect: { requests: [{ method: "GET", path: "/application/open-insight/pamirs-summary/download/file", query: { summaryId: "pam-1" } }] } },
    { title: "pamirs_summary：fileType 只收 1 / 2", args: { kind: "pamirs_summary", id: "pam-1", fileType: 3 }, expect: { rejects: /fileType 只收 1 \/ 2/ } },
    { title: "research", args: { kind: "research", id: "rep-1", fileType: 2 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/broker-report/download/file", query: { reportId: "rep-1", fileType: "2" } }] } },
    { title: "research：fileType 只收 1 / 2", args: { kind: "research", id: "rep-1", fileType: 4 }, expect: { rejects: /fileType 只收 1 \/ 2/ } },
    { title: "foreign_report", args: { kind: "foreign_report", id: "frep-1", fileType: 4 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/foreign-report/download/file", query: { reportId: "frep-1", fileType: "4" } }] } },
    { title: "foreign_report：不收 resourceType", args: { kind: "foreign_report", id: "frep-1", resourceType: 10 }, expect: { rejects: /不收 resourceType/ } },
    { title: "announcement", args: { kind: "announcement", id: "ann-1", fileType: 2 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/announcement/download/file", query: { announcementId: "ann-1", fileType: "2" } }] } },
    { title: "announcement：不收 contentType", args: { kind: "announcement", id: "ann-1", contentType: "summary" }, expect: { rejects: /不收 contentType/ } },
    { title: "announcement_hk", args: { kind: "announcement_hk", id: "annhk-1" }, expect: { requests: [{ method: "GET", path: "/application/open-insight/announcement-hk/download/file", query: { announcementId: "annhk-1" } }] } },
    { title: "announcement_hk：fileType 只收 1 / 2", args: { kind: "announcement_hk", id: "annhk-1", fileType: 3 }, expect: { rejects: /fileType 只收 1 \/ 2/ } },
    { title: "announcement_us", args: { kind: "announcement_us", id: "annus-1", fileType: 1 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/announcement-us/download/file", query: { announcementId: "annus-1", fileType: "1" } }] } },
    { title: "announcement_us：fileType 只收 1 / 2", args: { kind: "announcement_us", id: "annus-1", fileType: 4 }, expect: { rejects: /fileType 只收 1 \/ 2/ } },
    { title: "independent_opinion", args: { kind: "independent_opinion", id: "io-1", fileType: 2 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/independent-opinion/download/file", query: { independentOpinionId: "io-1", fileType: "2" } }] } },
    { title: "independent_opinion：fileType 必填", args: { kind: "independent_opinion", id: "io-1" }, expect: { rejects: /fileType 必填/ } },
    { title: "official_account", args: { kind: "official_account", id: "art-1", fileType: 2 }, expect: { requests: [{ method: "GET", path: "/application/open-insight/officialAccount/download/file", query: { articleId: "art-1", fileType: "2" } }] } },
    { title: "official_account：fileType 只收 1 / 2", args: { kind: "official_account", id: "art-1", fileType: 3 }, expect: { rejects: /fileType 只收 1 \/ 2/ } },
    { title: "report_image", args: { kind: "report_image", id: "chunk-1" }, expect: { requests: [{ method: "GET", path: "/application/open-insight/report-image/download/file", query: { chunkId: "chunk-1" } }] } },
    { title: "report_image：不收 fileType", args: { kind: "report_image", id: "chunk-1", fileType: 1 }, expect: { rejects: /不收 fileType/ } },
    { title: "performance_calendar", args: { kind: "performance_calendar", id: "perf-1" }, expect: { requests: [{ method: "GET", path: "/application/open-insight/schedule/performance-calendar/download/file", query: { performanceReportId: "perf-1" } }] } },
    { title: "performance_calendar：不收 fileType", args: { kind: "performance_calendar", id: "perf-1", fileType: 1 }, expect: { rejects: /不收 fileType/ } },
    { title: "knowledge_resource", args: { kind: "knowledge_resource", id: "src-1", resourceType: 10 }, expect: { requests: [{ method: "GET", path: "/application/open-data/ai/resource/download", query: { sourceId: "src-1", resourceType: "10" } }] } },
    { title: "knowledge_resource：resourceType 必填", args: { kind: "knowledge_resource", id: "src-1" }, expect: { rejects: /resourceType 必填/ } },
    { title: "drive", args: { kind: "drive", id: "file-1" }, expect: { requests: [{ method: "GET", path: "/application/open-vault/drive/download/file", query: { fileId: "file-1" } }] } },
    { title: "drive：不收 contentType", args: { kind: "drive", id: "file-1", contentType: "asr" }, expect: { rejects: /不收 contentType/ } },
    { title: "record", args: { kind: "record", id: "rec-1", contentType: "asr" }, expect: { requests: [{ method: "GET", path: "/application/open-vault/record/download/file", query: { recordId: "rec-1", contentType: "asr" } }] } },
    { title: "record：contentType 必填", args: { kind: "record", id: "rec-1" }, expect: { rejects: /contentType 必填/ } },
    { title: "my_conference", args: { kind: "my_conference", id: "conf-1", contentType: "summary" }, expect: { requests: [{ method: "GET", path: "/application/open-vault/my-conference/download/file", query: { conferenceId: "conf-1", contentType: "summary" } }] } },
    { title: "my_conference：contentType 只收 asr / summary", args: { kind: "my_conference", id: "conf-1", contentType: "original" }, expect: { rejects: /contentType 只收 asr \/ summary/ } },
    { title: "未知 kind 在 schema 层拒绝", args: { kind: "opinion", id: "x" }, expect: { rejects: /at kind/ } },
  ],
}
