import type { Billing, EndpointTable } from "../core/endpoints.js"

// 计分表未列帕米尔的两个接口，只写了「需购买专家纪要数据库」这个准入门槛。
const UNPRICED_PAMIRS: Billing = { kind: "unknown", note: "计分表未列，单价未公布（另需购买专家纪要数据库）" }

// ─── insight ───
export const insightEndpoints: EndpointTable = {
  // 观点列表两档：v2 只回标题与 200 字 brief（1/条），v1 带正文（30/条）。正文另可按 ID 取 detail。
  "insight.opinion.list": {
    method: "POST",
    path: "/application/open-insight/chief-opinion/v2/getList",
    kind: "json",
    description: "List domestic institution chief opinions (brief only)",
    billing: { kind: "fixed", per: "row", price: 1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "chiefOpinionId",
  },
  "insight.opinion.list-with-content": {
    method: "POST",
    path: "/application/open-insight/chief-opinion/getList",
    kind: "json",
    description: "List domestic institution chief opinions with full content",
    billing: { kind: "fixed", per: "row", price: 30, amplify: "单次约 600 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    retry: "no-replay",
  },
  "insight.opinion.detail": {
    method: "POST",
    path: "/application/open-insight/chief-opinion/getDetail",
    kind: "json",
    description: "Full content of domestic chief opinions by ID (at most 20 per call)",
    billing: { kind: "fixed", per: "row", price: 30, maxUnits: 20 },
    retry: "no-replay",
    expects: "array",
  },
  "insight.summary.list": {
    method: "POST",
    path: "/application/open-insight/summary/v2/getList",
    kind: "json",
    description: "List summaries",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "summaryId",
  },
  "insight.summary.download": {
    method: "GET",
    path: "/application/open-insight/summary/v2/download/file",
    kind: "download",
    description: "Download summary file",
    billing: { kind: "fixed", per: "document", price: 50 },
    retry: "no-replay",
  },
  "insight.pamirs-summary.list": {
    method: "POST",
    path: "/application/open-insight/pamirs-summary/getList",
    kind: "json",
    description: "List Pamirs expert summaries (requires the expert-summary database)",
    billing: UNPRICED_PAMIRS,
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "summaryId",
  },
  "insight.pamirs-summary.download": {
    method: "GET",
    path: "/application/open-insight/pamirs-summary/download/file",
    kind: "download",
    description: "Download a Pamirs expert summary file",
    billing: UNPRICED_PAMIRS,
    // The 2026-08-07 spec states an entitlement (the expert-summary database) but
    // no per-call price. Treated as non-idempotent anyway, like its
    // insight.summary.download sibling: if it does meter, a 5xx replay
    // double-bills, and the only cost of being wrong is losing one retry.
    retry: "no-replay",
  },
  "insight.roadshow.list": {
    method: "POST",
    path: "/application/open-insight/schedule/roadshow/getList",
    kind: "json",
    description: "List roadshows",
    billing: { kind: "fixed", per: "row", price: 20, amplify: "单次约 400 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "id",
    rowIdUnverified: true,
  },
  "insight.site-visit.list": {
    method: "POST",
    path: "/application/open-insight/schedule/site-visit/getList",
    kind: "json",
    description: "List site visits",
    billing: { kind: "fixed", per: "row", price: 20, amplify: "单次约 400 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "id",
    rowIdUnverified: true,
  },
  "insight.strategy.list": {
    method: "POST",
    path: "/application/open-insight/schedule/strategy-meeting/getList",
    kind: "json",
    description: "List strategy meetings",
    billing: { kind: "fixed", per: "row", price: 20, amplify: "单次约 400 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "id",
    rowIdUnverified: true,
  },
  "insight.forum.list": {
    method: "POST",
    path: "/application/open-insight/schedule/forum/getList",
    kind: "json",
    description: "List forums",
    billing: { kind: "fixed", per: "row", price: 20, amplify: "单次约 400 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "id",
    rowIdUnverified: true,
  },
  "insight.performance-calendar.list": {
    method: "POST",
    path: "/application/open-insight/schedule/performance-calendar/getList",
    kind: "json",
    description: "List earnings calendar events (forecast / express / announcement)",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "performanceReportId",
  },
  "insight.performance-calendar.download": {
    method: "GET",
    path: "/application/open-insight/schedule/performance-calendar/download/file",
    kind: "download",
    description: "Download an earnings report file (A-share 10 credits, HK/US 20)",
    // 唯一按标的市场分档的下载：A股 10、港美股 20。标签词表没有「按市场分档」这一档，
    // 按 20 统一报价会误导模型，所以标签取较低的 A 股档，港美股档走 amplify 尾注。
    billing: { kind: "fixed", per: "document", price: 10, amplify: "港美股为 20/条" },
  },
  "insight.research.list": {
    method: "POST",
    path: "/application/open-insight/broker-report/getList",
    kind: "json",
    description: "List broker research reports",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "reportId",
  },
  "insight.research.download": {
    method: "GET",
    path: "/application/open-insight/broker-report/download/file",
    kind: "download",
    description: "Download broker research report",
    billing: { kind: "fixed", per: "document", price: 10 },
  },
  "insight.foreign-report.list": {
    method: "POST",
    path: "/application/open-insight/foreign-report/getList",
    kind: "json",
    description: "List foreign reports",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "reportId",
  },
  "insight.foreign-report.download": {
    method: "GET",
    path: "/application/open-insight/foreign-report/download/file",
    kind: "download",
    description: "Download foreign report",
    billing: { kind: "fixed", per: "document", price: 50 },
    retry: "no-replay",
  },
  "insight.announcement.list": {
    method: "POST",
    path: "/application/open-insight/announcement/getList",
    kind: "json",
    description: "List A-share announcements",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "announcementId",
  },
  "insight.announcement.download": {
    method: "GET",
    path: "/application/open-insight/announcement/download/file",
    kind: "download",
    description: "Download A-share announcement file",
    billing: { kind: "fixed", per: "document", price: 10 },
  },
  "insight.announcement-hk.list": {
    method: "POST",
    path: "/application/open-insight/announcement-hk/getList",
    kind: "json",
    description: "List HK announcements",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "announcementId",
  },
  "insight.announcement-hk.download": {
    method: "GET",
    path: "/application/open-insight/announcement-hk/download/file",
    kind: "download",
    description: "Download HK announcement file",
    billing: { kind: "fixed", per: "document", price: 20 },
  },
  "insight.announcement-us.list": {
    method: "POST",
    path: "/application/open-insight/announcement-us/getList",
    kind: "json",
    description: "List US announcements",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "announcementId",
  },
  "insight.announcement-us.download": {
    method: "GET",
    path: "/application/open-insight/announcement-us/download/file",
    kind: "download",
    description: "Download US announcement file",
    billing: { kind: "fixed", per: "document", price: 20 },
  },
  "insight.foreign-opinion.list": {
    method: "POST",
    path: "/application/open-insight/foreign-opinion/v2/getList",
    kind: "json",
    description: "List foreign institution opinions (brief only)",
    billing: { kind: "fixed", per: "row", price: 1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "foreignOpinionId",
  },
  "insight.foreign-opinion.list-with-content": {
    method: "POST",
    path: "/application/open-insight/foreign-opinion/getList",
    kind: "json",
    description: "List foreign institution opinions with full content",
    billing: { kind: "fixed", per: "row", price: 30, amplify: "单次约 600 积分" },
    pagination: { mode: "offset", maxPageSize: 50 },
    retry: "no-replay",
  },
  "insight.foreign-opinion.detail": {
    method: "POST",
    path: "/application/open-insight/foreign-opinion/getDetail",
    kind: "json",
    description: "Full content of foreign opinions by ID (at most 20 per call)",
    billing: { kind: "fixed", per: "row", price: 30, maxUnits: 20 },
    retry: "no-replay",
    expects: "array",
  },
  "insight.independent-opinion.list": {
    method: "POST",
    path: "/application/open-insight/independent-opinion/getList",
    kind: "json",
    description: "List foreign independent analyst opinions",
    billing: { kind: "fixed", per: "row", price: 5 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "independentOpinionId",
    rowIdUnverified: true,
  },
  "insight.independent-opinion.download": {
    method: "GET",
    path: "/application/open-insight/independent-opinion/download/file",
    kind: "download",
    description: "Download foreign independent opinion file",
    billing: { kind: "fixed", per: "document", price: 30 },
  },
  "insight.official-account.list": {
    method: "POST",
    path: "/application/open-insight/officialAccount/getList",
    kind: "json",
    description: "List WeChat official account articles",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 50 },
    rowId: "articleId",
  },
  "insight.official-account.download": {
    method: "GET",
    path: "/application/open-insight/officialAccount/download/file",
    kind: "download",
    description: "Download WeChat official account article (txt/HTML)",
    billing: { kind: "fixed", per: "document", price: 10 },
  },
  "insight.qa.list": {
    method: "POST",
    // The literal '&' is the vendor's path segment (Q&A-data), not a query separator.
    path: "/application/open-insight/Q&A-data/getList",
    kind: "json",
    description: "List investor Q&A (conference/interactive/survey) for a security",
    billing: { kind: "fixed", per: "row", price: 0.1 },
    pagination: { mode: "offset", maxPageSize: 500 },
  },
  "insight.report-image.list": {
    method: "POST",
    path: "/application/open-insight/report-image/getList",
    kind: "json",
    description: "Search research report images by keyword (returns chunkId + metadata)",
    billing: { kind: "free" },
  },
  "insight.report-image.download": {
    method: "GET",
    path: "/application/open-insight/report-image/download/file",
    kind: "download",
    description: "Download a research report image by chunkId",
    billing: { kind: "fixed", per: "document", price: 0.1, unit: "张" },
  },
}
