import fs from "node:fs/promises"
import path from "node:path"

import { z } from "zod"
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import type { GangtiseClient } from "../core/client.js"
import { errorMessage } from "../core/errors.js"
import { isOwnedTempPath } from "../core/tempCleanup.js"
import { INLINE_MAX_BYTES } from "../core/config.js"
import { alignSliceEnd } from "./registry.js"
import { withBilling } from "./billing.js"

const DEFAULT_LIMIT = 50
const MAX_LIMIT = 500
/** Per-call character window for raw text / large-object chunk payloads. Derived
 * from INLINE_MAX_BYTES so a chunk of worst-case 3-byte UTF-8 chars (e.g. Chinese —
 * the max per UTF-16 unit) still fits the inline budget: 0.27 × budget × 3 ≈ 0.81 ×
 * budget, leaving headroom for the JSON envelope. JSON.stringify never escapes
 * multibyte chars, so non-ASCII is the byte-worst case here. Exported for tests that
 * construct fixtures on the chunk boundary. INLINE_MAX_BYTES is the byte-based spill
 * threshold, shared with registry.ts via config.js. */
export const TEXT_CHUNK_CHARS = Math.floor(INLINE_MAX_BYTES * 0.27)

async function readSavedFile(savedTo: string): Promise<string> {
  let real: string
  try {
    real = await fs.realpath(savedTo)
  } catch {
    throw new Error(`saved_to path not found: ${savedTo}`)
  }
  // Only files this server process wrote (gangtise-mcp- temp dirs created via
  // createManagedTempDir) are readable — blocks reading arbitrary tmp files.
  if (!isOwnedTempPath(real)) {
    throw new Error("saved_to must be a gangtise-mcp- temp file generated by this server process")
  }
  // Reading proves an active session still needs this spill dir — refresh its
  // mtime so a second instance's 24h startup sweep won't reclaim it mid-read.
  await fs.utimes(path.dirname(real), new Date(), new Date()).catch(() => {})
  return fs.readFile(real, "utf8")
}

export function registerResponseTools(server: McpServer, _client: GangtiseClient): void {
  server.registerTool(
    "gangtise_read_response",
    {
      description: withBilling(
        "gangtise_read_response",
        "读取被截断的大响应。当其他工具返回 `_truncated: true` 且包含 `_saved_to` 临时文件路径时，用此工具按 offset/limit 分片读取完整数据。仅可读取本进程在系统临时目录下生成的 gangtise-mcp- 前缀文件。",
      ),
      inputSchema: {
        saved_to: z
          .string()
          .describe("被截断响应的临时文件路径（来自其他工具响应中的 _saved_to 字段）"),
        offset: z
          .number()
          .int()
          .min(0)
          .optional()
          .describe("起始条目索引（从 0 开始），默认 0"),
        limit: z
          .number()
          .int()
          .min(1)
          .max(MAX_LIMIT)
          .optional()
          .describe(`本次返回的条目数，默认 ${DEFAULT_LIMIT}，最大 ${MAX_LIMIT}`),
      },
      annotations: { readOnlyHint: true, openWorldHint: false },
    },
    async ({ saved_to, offset = 0, limit = DEFAULT_LIMIT }) => {
      try {
        const raw = await readSavedFile(saved_to)

        let data: unknown
        try {
          data = JSON.parse(raw)
        } catch {
          // Raw text payload (Markdown/HTML) — slice by character offset.
          const total = raw.length
          const start = Math.min(offset, total)
          const end = alignSliceEnd(raw, Math.min(start + TEXT_CHUNK_CHARS, total))
          const slice = raw.slice(start, end)
          const payload = {
            _text: slice,
            _saved_to: saved_to,
            _total_chars: total,
            _offset: start,
            _returned: slice.length,
            has_more: end < total,
            next_offset: end < total ? end : null,
            _note: `纯文本分片：按字符 offset 读取，每次返回最多 ${TEXT_CHUNK_CHARS} 字符（limit 对文本无效）`,
          }
          return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
        }

        let list: unknown[]
        let rest: Record<string, unknown> = {}
        if (Array.isArray(data)) {
          list = data
        } else if (
          data !== null &&
          typeof data === "object" &&
          Array.isArray((data as Record<string, unknown>).list)
        ) {
          const obj = data as Record<string, unknown>
          list = obj.list as unknown[]
          rest = Object.fromEntries(Object.entries(obj).filter(([k]) => k !== "list"))
        } else {
          // Non-list object. A small one is returned whole; a large one (e.g. a
          // object over INLINE_MAX_BYTES that was spilled with a metadata-only preview) is char-sliced
          // so read-back can't re-inline the whole blob and defeat the truncation.
          const objText = JSON.stringify(data)
          if (Buffer.byteLength(objText, "utf8") > INLINE_MAX_BYTES) {
            const total = objText.length
            const start = Math.min(offset, total)
            const end = alignSliceEnd(objText, Math.min(start + TEXT_CHUNK_CHARS, total))
            const slice = objText.slice(start, end)
            const payload = {
              _json_chunk: slice,
              _saved_to: saved_to,
              _total_chars: total,
              _offset: start,
              _returned: slice.length,
              has_more: end < total,
              next_offset: end < total ? end : null,
              _note: `大对象按字符 offset 分片：每次最多 ${TEXT_CHUNK_CHARS} 字符，拼接各片得到完整 JSON（limit 对此形状无效）`,
            }
            return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
          }
          const payload = {
            data,
            _saved_to: saved_to,
            _total_items: null,
            _offset: 0,
            _returned: 1,
            has_more: false,
            next_offset: null,
          }
          return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
        }

        const total = list.length
        const start = Math.min(offset, total)
        const hardEnd = Math.min(start + limit, total)
        // Byte-budget the page too: rows can be tens of KB each (announcement
        // full text), so an item-count window alone could inline megabytes —
        // the very thing the spill mechanism exists to prevent. Always advances
        // by at least one item so paging can't stall on an oversized row.
        let end = start
        let sliceBytes = 0
        while (end < hardEnd) {
          sliceBytes += Buffer.byteLength(JSON.stringify(list[end]), "utf8")
          if (end > start && sliceBytes > INLINE_MAX_BYTES) break
          end += 1
        }
        const slice = list.slice(start, end)

        const payload = {
          ...rest,
          list: slice,
          _saved_to: saved_to,
          _total_items: total,
          _offset: start,
          _returned: slice.length,
          has_more: end < total,
          next_offset: end < total ? end : null,
          ...(end < hardEnd
            ? { _note: `本页按 ${Math.round(INLINE_MAX_BYTES / 1024)}KB 字节预算返回 ${slice.length} 条（少于请求的 limit），用 next_offset 继续翻页` }
            : {}),
        }

        return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
      } catch (err) {
        return { content: [{ type: "text" as const, text: errorMessage(err) }], isError: true }
      }
    },
  )
}
