import fs from "node:fs/promises"
import path from "node:path"

import { z } from "zod"
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import type { GangtiseClient } from "../core/client.js"
import { errorMessage, ValidationError } from "../core/errors.js"
import { isOwnedTempPath } from "../core/tempCleanup.js"
import { INLINE_MAX_BYTES } from "../core/config.js"
import { alignSliceEnd } from "./registry.js"
import { withBilling } from "./billing.js"

const DEFAULT_LIMIT = 50
const MAX_LIMIT = 500
/** Per-call character window for raw text / large-object chunk payloads. Derived
 * from INLINE_MAX_BYTES so a chunk of worst-case 3-byte UTF-8 chars (e.g. Chinese —
 * the max per UTF-16 unit) still fits the inline budget: 0.27 × budget × 3 ≈ 0.81 ×
 * budget, leaving headroom for the JSON envelope. JSON.stringify never escapes
 * multibyte chars, so non-ASCII is the byte-worst case here. Exported for tests that
 * construct fixtures on the chunk boundary. INLINE_MAX_BYTES is the byte-based spill
 * threshold, shared with registry.ts via config.js. */
export const TEXT_CHUNK_CHARS = Math.floor(INLINE_MAX_BYTES * 0.27)

/** 本页少于请求 limit 时附在 payload 上的说明。信封预估也要带上它。
 *  导出供测试直接引用，避免测试逐字复刻本文案造成同源漂移（见 response.test.ts 用例 d）。 */
export function pageNote(returned: number): string {
  return `本页按 ${Math.round(INLINE_MAX_BYTES / 1024)}KB 字节预算返回 ${returned} 条（少于请求的 limit），用 next_offset 继续翻页`
}

const FIELDS_MAX = 50
const FIELD_NAME_MAX = 64
const UNKNOWN_FIELDS_ECHO_MAX = 20

/** 顶层投影。用 Object.hasOwn 读、Object.create(null) 造 ——
 *  防 __proto__/constructor 这类继承键被当成数据带出或污染原型。 */
function projectRow(row: Record<string, unknown>, fields: string[]): Record<string, unknown> {
  const out = Object.create(null) as Record<string, unknown>
  for (const field of fields) {
    if (Object.hasOwn(row, field)) out[field] = row[field]
  }
  return out
}

/** 未知字段 = 在**全部行**里都不存在的请求字段。
 *  判定范围必须是全量，不是溢出指针那 20 行采样窗口 ——
 *  否则只出现在第 21 行的稀疏字段会被误判成拼写错误。
 *  逐行剔除待查集，常见情况第一行就查完并提前退出。 */
function findUnknownFields(list: unknown[], fields: string[]): string[] {
  const pending = new Set(fields)
  for (const row of list) {
    if (!row || typeof row !== "object" || Array.isArray(row)) continue
    for (const field of [...pending]) {
      if (Object.hasOwn(row as object, field)) pending.delete(field)
    }
    if (pending.size === 0) break
  }
  return [...pending]
}

/** 报错时回列的可用字段，取前若干行、最多 UNKNOWN_FIELDS_ECHO_MAX 个，防错误消息自身膨胀。 */
function sampleFieldNames(list: unknown[]): string[] {
  const names: string[] = []
  for (const row of list.slice(0, 20)) {
    if (!row || typeof row !== "object" || Array.isArray(row)) continue
    for (const key of Object.keys(row as object)) {
      if (!names.includes(key)) names.push(key)
      if (names.length >= UNKNOWN_FIELDS_ECHO_MAX) return names
    }
  }
  return names
}

async function readSavedFile(savedTo: string): Promise<string> {
  let real: string
  try {
    real = await fs.realpath(savedTo)
  } catch {
    throw new Error(`saved_to path not found: ${savedTo}`)
  }
  // Only files this server process wrote (gangtise-mcp- temp dirs created via
  // createManagedTempDir) are readable — blocks reading arbitrary tmp files.
  if (!isOwnedTempPath(real)) {
    throw new Error("saved_to must be a gangtise-mcp- temp file generated by this server process")
  }
  // Reading proves an active session still needs this spill dir — refresh its
  // mtime so a second instance's 24h startup sweep won't reclaim it mid-read.
  await fs.utimes(path.dirname(real), new Date(), new Date()).catch(() => {})
  return fs.readFile(real, "utf8")
}

export function registerResponseTools(server: McpServer, _client: GangtiseClient): void {
  server.registerTool(
    "gangtise_read_response",
    {
      description: withBilling(
        "gangtise_read_response",
        "读取被截断的大响应。当其他工具返回 `_truncated: true` 且包含 `_saved_to` 临时文件路径时，用此工具按 offset/limit 分片读取完整数据。仅可读取本进程在系统临时目录下生成的 gangtise-mcp- 前缀文件。",
      ),
      inputSchema: {
        saved_to: z
          .string()
          .describe("被截断响应的临时文件路径（来自其他工具响应中的 _saved_to 字段）"),
        offset: z
          .number()
          .int()
          .min(0)
          .optional()
          .describe("起始条目索引（从 0 开始），默认 0"),
        limit: z
          .number()
          .int()
          .min(1)
          .max(MAX_LIMIT)
          .optional()
          .describe(`本次返回的条目数，默认 ${DEFAULT_LIMIT}，最大 ${MAX_LIMIT}`),
        fields: z
          .array(
            z
              .string()
              .trim()
              .min(1, "fields 项不能为空")
              .max(FIELD_NAME_MAX, `fields 单项最长 ${FIELD_NAME_MAX} 字符`),
          )
          .min(1)
          .max(FIELDS_MAX, `fields 最多 ${FIELDS_MAX} 项`)
          .refine((v) => new Set(v).size === v.length, "fields 不能重复")
          .optional()
          .describe("只返回这些顶层字段（不支持点路径）；宽表按需投影可显著减少回读进上下文的字节"),
      },
      annotations: { readOnlyHint: true, openWorldHint: false },
    },
    async ({ saved_to, offset = 0, limit = DEFAULT_LIMIT, fields }) => {
      try {
        const raw = await readSavedFile(saved_to)

        let data: unknown
        try {
          data = JSON.parse(raw)
        } catch {
          // Raw text payload (Markdown/HTML) — slice by character offset.
          if (fields) throw new ValidationError("fields 仅适用于 JSON 列表响应，该文件是纯文本；去掉 fields 后重试。")
          const total = raw.length
          const start = Math.min(offset, total)
          const end = alignSliceEnd(raw, Math.min(start + TEXT_CHUNK_CHARS, total))
          const slice = raw.slice(start, end)
          const payload = {
            _text: slice,
            _saved_to: saved_to,
            _total_chars: total,
            _offset: start,
            _returned: slice.length,
            has_more: end < total,
            next_offset: end < total ? end : null,
            _note: `纯文本分片：按字符 offset 读取，每次返回最多 ${TEXT_CHUNK_CHARS} 字符（limit 对文本无效）`,
          }
          return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
        }

        let list: unknown[]
        let rest: Record<string, unknown> = {}
        if (Array.isArray(data)) {
          list = data
        } else if (
          data !== null &&
          typeof data === "object" &&
          Array.isArray((data as Record<string, unknown>).list)
        ) {
          const obj = data as Record<string, unknown>
          list = obj.list as unknown[]
          rest = Object.fromEntries(Object.entries(obj).filter(([k]) => k !== "list"))
        } else {
          if (fields) throw new ValidationError("fields 仅适用于 JSON 列表响应，该文件是非列表对象；去掉 fields 后重试。")
          // Non-list object. A small one is returned whole; a large one (e.g. a
          // object over INLINE_MAX_BYTES that was spilled with a metadata-only preview) is char-sliced
          // so read-back can't re-inline the whole blob and defeat the truncation.
          const objText = JSON.stringify(data)
          if (Buffer.byteLength(objText, "utf8") > INLINE_MAX_BYTES) {
            const total = objText.length
            const start = Math.min(offset, total)
            const end = alignSliceEnd(objText, Math.min(start + TEXT_CHUNK_CHARS, total))
            const slice = objText.slice(start, end)
            const payload = {
              _json_chunk: slice,
              _saved_to: saved_to,
              _total_chars: total,
              _offset: start,
              _returned: slice.length,
              has_more: end < total,
              next_offset: end < total ? end : null,
              _note: `大对象按字符 offset 分片：每次最多 ${TEXT_CHUNK_CHARS} 字符，拼接各片得到完整 JSON（limit 对此形状无效）`,
            }
            return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
          }
          const payload = {
            data,
            _saved_to: saved_to,
            _total_items: null,
            _offset: 0,
            _returned: 1,
            has_more: false,
            next_offset: null,
          }
          return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
        }

        const total = list.length
        const start = Math.min(offset, total)
        const hardEnd = Math.min(start + limit, total)

        let unknownFields: string[] = []
        if (fields) {
          // 非对象检查只看**本页窗口** [start, hardEnd)，不是整个文件：远在第 9000 行的
          // 一个坏行不该让第 0 页的投影失败——那恰是 fields 要服务的场景。投影只发生在
          // 窗口内（projectRow 仅对窗口行调用），窗口外的坏行由 findUnknownFields 的
          // 非对象跳过逻辑安全略过。这与 _unknown_fields 必须扫全量（防稀疏字段误杀）
          // 不同：非对象判定没有全量的必要。
          if (list.slice(start, hardEnd).some((r) => r === null || typeof r !== "object" || Array.isArray(r))) {
            throw new ValidationError("fields 仅适用于对象行列表，本页窗口含非对象元素；去掉 fields 后重试。")
          }
          // 空列表无从判定字段合法性 —— 正常返回空结果，不判未知字段。
          if (list.length > 0) {
            unknownFields = findUnknownFields(list, fields)
            // 逐字段判定：部分未知照常返回并回显，只有全部未知才算调用错了。
            // 「全都没有才报错」会静默吞掉 ["securityCode","clsoe"] 里拼错的那个。
            if (unknownFields.length === fields.length) {
              throw new ValidationError(
                `fields 全部不存在于数据中：${unknownFields.join("、")}。可用字段（最多 ${UNKNOWN_FIELDS_ECHO_MAX} 个）：${sampleFieldNames(list).join("、")}`,
              )
            }
          }
        }

        // 字节预算必须算上信封（...rest + _saved_to/_total_items/_note 等），
        // 不能只算行字节：实测单行 65,509B 未超限，拼上信封后 payload 65,779B 已超限 ——
        // 只算行的旧写法会让这类载荷整个溜过检查。信封按最宽情形估：_note 常驻、
        // 数字取最大位宽、has_more/next_offset 取真实两态（末页 vs 非末页）中更宽的
        // 一种，估多不估少，保证最终 payload 一定 ≤ 预算。
        const envelopeBytes = Buffer.byteLength(
          JSON.stringify({
            ...rest,
            list: [],
            _saved_to: saved_to,
            _total_items: total,
            _offset: start,
            _returned: hardEnd - start,
            // 估多不估少：has_more 取 'false'(5B)、next_offset 取 'null'(4B) 与 total 位宽的较大者
            has_more: false,                                        // 5B > 'true' 的 4B
            next_offset: String(total).length >= 4 ? total : null,  // 取更宽的那个
            _note: pageNote(hardEnd - start),
            ...(fields ? { _fields: fields } : {}),
            ...(unknownFields.length > 0 ? { _unknown_fields: unknownFields } : {}),
          }),
          "utf8",
        )
        const rowBudget = INLINE_MAX_BYTES - envelopeBytes

        // 至少推进一条，翻页不会卡死。JSON 数组的分隔逗号也占字节，一并计入。
        // 投影先于预算：projectRow 后的行才拿去算字节，宽表窄投影因此每页能装更多行。
        let end = start
        let sliceBytes = 0
        const slice: unknown[] = []
        while (end < hardEnd) {
          const row = fields ? projectRow(list[end] as Record<string, unknown>, fields) : list[end]
          const rowBytes = Buffer.byteLength(JSON.stringify(row), "utf8") + (end > start ? 1 : 0)
          if (end > start && sliceBytes + rowBytes > rowBudget) break
          sliceBytes += rowBytes
          slice.push(row)
          end += 1
        }

        const payload: Record<string, unknown> = {
          ...rest,
          list: slice,
          _saved_to: saved_to,
          _total_items: total,
          _offset: start,
          _returned: slice.length,
          has_more: end < total,
          next_offset: end < total ? end : null,
          ...(end < hardEnd ? { _note: pageNote(slice.length) } : {}),
          ...(fields ? { _fields: fields } : {}),
          ...(unknownFields.length > 0 ? { _unknown_fields: unknownFields } : {}),
        }

        // (b) 信封 + 最小一行仍超预算，或 (c) 零行但 rest 自己就超预算：
        // 原样返回并显式标记。不截断 rest（非列表、无分页语义，截了会静默丢数据），
        // 也不退化成 metadata-only（现状就是「返回一行」，改掉属破坏性变更）。
        if (Buffer.byteLength(JSON.stringify(payload), "utf8") > INLINE_MAX_BYTES) {
          payload._oversized = true
        }

        return { content: [{ type: "text" as const, text: JSON.stringify(payload) }] }
      } catch (err) {
        return { content: [{ type: "text" as const, text: errorMessage(err) }], isError: true }
      }
    },
  )
}
